from distutils.core import setup

setup(name='kinetic-cme-scripts',
      version='1.0',
      description='Scripts for generating input files and plotting output files',
      py_modules = ['scripts.models.bax',
                    'scripts.models.bax_pysb',
                    'scripts.models.enzymatic_futile_cycle',
                    'scripts.models.enzymatic_futile_cycle_gillespy',
                    'scripts.models.enzymatic_futile_cycle_pysb',
                    'scripts.models.lambda_phage',
                    'scripts.models.lambda_phage_gillespy',
                    'scripts.models.lambda_phage_pysb',
                    'scripts.models.diffusive_toggle_switch',
                    'scripts.models.diffusive_toggle_switch_gillespy',
                    'scripts.models.diffusive_toggle_switch_pysb',
                    'scripts.models.toggle_switch',
                    'scripts.models.toggle_switch_gillespy',
                    'scripts.id_class',
                    'scripts.initial_condition_class',
                    'scripts.index_functions',
                    'scripts.grid_class',
                    'scripts.reaction_class',
                    'scripts.tree_class']
      )
